### ISSUE TITLE
[REVIEW] Extend tests for core functionalities

### ISSUE THREAD

**Issue by santisoler** [brmather/pycurious#27] opened 2019-07-15 15:22 UTC
Part of https://github.com/openjournals/joss-reviews/issues/1544.

Because `pycurious` relies on processing the magnetic data in order to compute the CDP:
- read/load magnetic grid,
- select a subgrid,
- compute FFT and its radial average,
- apply tappering and
- estimate depths to magnetic sources,

I consider relevant to extend tests for the core computations, just to make sure they work as expected and to prevent breaking anything on future changes.
The current test functions only test if the methods don't fail when run. That's important, but I think is also mandatory to check if they are working as expected.
I don't intent you to achieve a 100% coverage, but just add tests that assert if the result is close to the expected one.

Besides individual tests for each method, would be nice to add a synthetic magnetic data (with known depths of the magnetic source) and check if Tanaka and Bouligand methods recover the original depths.

What do you think? Do you agree?

**Comment by brmather** [comment] 2019-07-17 02:02
Thanks for bringing this to my attention. In 0c0bca645757248c8c6727582b422b72916e7060 I've populated the test suite with core functionality tests to make sure these routine are working as expected. These tests read in a synthetic magnetic anomaly generated with a known fractal parameter and CPD. To summise:

- `test_subgrid` tests if a subgrid can be extracted from the total extent. The test passes if the subgrid is smaller than `mesh.data`.
- `test_FFT` tests if the FFT produces a radial power spectrum of a reasonable shape. Expected behaviour is that the spectrum must decrease with higher wavenumber (uncertainties should also decrease with wavenumber).
- `test_taper_functions` compares the shape of the radial power spectrum using a `np.hanning` and `np.hamming` window to no taper function. The tapered spectrum should have a lower average gradient.
- `test_Tanaka` tests whether a sensible solution of CPD can be extracted from a magnetic grid of known CPD using the Tanaka method.
- `test_optimisation` tests whether a sensible solution of CPD can be inverted from a magnetic grid of known CPD and fractal parameter, using the Bouligand method.
- `test_priors` compares the optimisation with and without *a priori* information. The test passes if the optimisation returns values closer to the _a priori_ distributions.

Please let me know if you can think of any improvements to these tests, or if you can think of any additional ones. I prefer not to test the `pycurious.mapping` module since its dependencies are optional.

**Comment by santisoler** [comment] 2019-07-17 13:59
That's great @brmather! I like it very much now. I would incorporate some best practices for writing test functions.
For example, there's no need to add the `if else` statements. You could just use `assert` or `numpy.testing.assert_allclose` if you want to compare numerical results.

For example, on `test_subgrid()`:
https://github.com/brmather/pycurious/blob/0c0bca645757248c8c6727582b422b72916e7060/tests/test_grid.py#L25-L34

I would change it to:
```python
def test_subgrid():
    grid = pycurious.CurieGrid(d, xmin, xmax, ymin, ymax)

    window_size = 100e3
    subgrid = grid.subgrid(window_size, xc, yc)

    assert subgrid.shape[0] < grid.data.shape[0]
    assert subgrid.shape[1] < grid.data.shape[1]
```

Or `test_optimisation()`:
https://github.com/brmather/pycurious/blob/0c0bca645757248c8c6727582b422b72916e7060/tests/test_optimise.py#L29-L49

It may be changed to:
```python
import numpy.testing as npt

def test_optimisation():
    grid = pycurious.CurieOptimise(d, xmin, xmax, ymin, ymax)
    beta, zt, dz, C = grid.optimise(max_window, xc, yc, taper=np.hanning)

    x_opt = np.array([beta, zt, dz])

    # hard-coded parameters used to generate the magnetic anomaly
    zt0 = 0.305
    dz0 = 10.0 + zt0
    beta0 = 3.0

    x0 = np.array([beta0, zt0, dz0])

    # compare if they are close or not
    # some parameters should be more similar than others
    tol = np.array([0.3, 0.1, 2.0])
    
    for i in range(x0.size):
        npt.assert_allclose(x_opt[i], x[i], atol=tol[i])
```

Besides, all the global variables defined at the beginning of the files can be grouped inside a [pytest fixture](https://docs.pytest.org/en/latest/reference.html?highlight=fixture#fixtures). That way you prevent to accidentally modify them (and possible headaches in the future). Because you would need more than one element (`x`, `y`, `d`, etc) you could return a dictionary containing these arrays.

Let me know if you need any help with these!

**Comment by santisoler** [comment] 2019-07-17 14:01
By the way, are `xc` and `yc` the coordinates of the center of the subgrid?
https://github.com/brmather/pycurious/blob/0c0bca645757248c8c6727582b422b72916e7060/tests/test_optimise.py#L22-L23

If that's the case, shouldn't those minus signs be plus signs?

**Comment by brmather** [comment] 2019-07-18 02:10
Thanks @santisoler I appreciate those `if else` statements were not very useful. I've refactored the tests in 09ae019f43389e56db3c4e4ebada092b68114260 using a `pytest.fixture` to load in the magnetic grid. That's a much better way of doing it than loading it in at the start of each test script - `pytest` is great!

Also, the assertion statements are now enriched with information on the error. Take your `test_optimisation` for example, before the test would compare if the inverted parameters were within their tolerances all at once, but now it iterates through them individually making debugging a whole lot easier. I was also not aware of the `numpy.testing` module either. It provides a lot of useful information that is missing from the standard `assert` statement. I will use this for other tests in the future.

**Comment by brmather** [comment] 2019-07-18 02:13
> By the way, are `xc` and `yc` the coordinates of the center of the subgrid?

You are right! It must have been late in the afternoon... :sweat_smile: It didn't impact on the tests because `xmin=0` and `ymin=0`, but it's fixed now. :+1:

**Comment by santisoler** [comment] 2019-07-18 13:35
Great @brmather! I like it very much now! I think we can close this issue now.

Just wanted to leave you some tips for the future based on my experience and what I've learned developing Fatiando a Terra.

1. I think you are very skilled on coding and documenting the code. Writing the documentation before or while you write the code is one of the best practices, and you master it very well. A good advice is to write the code thinking on how you will test it. I know it's not easy at first, but is a good practice to take this into account while you are designing your code. Besides, it's good to write the test functions at the same time you write the code. So any new commit (or PR) will be based on three legs: code, documentation and tests.

1. I like how you linked commits on issues. It really helped me to track down changes. Nevertheless, you are missing one of the greatest tools that GitHub has by doing it: Pull Requests. At the beginning I think I felt the same way about PRs: *they are intended to contributors to share code*. Although that's true, contributors **must** open PRs when sharing code, opening PRs by repo owners it's an amazing tool: 
    - They help you tracking changes (think your present self as a completely stranger for the future you, I'm sure you are not going to remember why did you added *that line* one year ago).
    - They make the developing process much transparent to others. You could ask for review to any other contributor (or even reviewer in case you submitted it to JOSS).
    - They make much easier to develop in parallel. Many contributors can still continue coding without worrying about random commits that are pushed into master.
    - They move the specific code discussion to the PR rather than having them on the issues. This helps to organize your discussions better, but also the PRs interface gives you a lot of tools: review, suggest changes, don't allow merge until PR is accepted by reviewer, etc.
    - They also offer the option to **Squash and Merge**. It squashes all commits inside the PR into a single one and then merge it into master. That way, running `git log` on master gives you a very concise history of changes, without ugly commit messages like "Experimenting with this new stuff" or "Fixed some typos".

    So, the workflow for **any** contributor (owners included) could be:
      1. Open an issue asking to solve a bug or asking for a new feature. Even though if you are going to fix it right away. It's a good practice of tracking down why you though *that bug* or *that new feature* must be tackled down.
      1. Open a PR with the new code solving that issue. Remember to link the issue on the PR message. The PR must have well written code with documentation and tests functions. If CI is configured, it must pass.
      1. Ask for review to any other contributor. Discuss modifications on the PR interface.
      1. When the PR is ready to be merged, Squash and Merge. Write a well explained commit message to summarize what the new code does.

1. A little thing regarding styling. Although Python is capable of understanding very different code styles, it's a good practice to follow common styling. One of the common Guiding Styles is [PEP8](https://www.python.org/dev/peps/pep-0008/). A few years ago I used to fix PEP8 errors by hand, although now days there's a tool that I love: [Black](https://github.com/python/black). It automatically reformat your code to meet PEP8 requirements, but also adds some own code styles that minimize the diffs and improve readability.

Hope these little tips can be useful! Take them as guidelines. I learned (and still learning) how to develop code by doing it and failing a lot, so feel free to correct me if you think something is wrong with them, or if you think there's a better way to do these things.

**Comment by brmather** [comment] 2019-07-18 14:04
I appreciate your wisdom in these areas - thank you @santisoler! Your review has taught me a lot of good practises for writing and maintaining code collaboratively. For instance, I didn't know that writing Fix <issue #> in a pull request would automatically link and close the issue once the PR was accepted - very nifty!

There are many other extremely useful things I have learnt, but I would say the practise of opening a PR for code changes is an extremely valuable tool in a programmers' arsenal. Even if there are few developers, the checks and balances on pull request using CI are invaluable. As I am becoming more confident with git (and specifically GitHub) I'm rolling out this practise to all the other projects I am involved in.

`Black` looks like a very neat package, I'll take it for a test run soon. If you come across any other tools you think are great, please don't hesitate to reach out!

**Closed** 2019-07-18 14:04 UTC
